baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Kross | Hugo Portfolio Template"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "The Blockchain"
author = ""
copyright = "Copyright &copy; 2020 a theme by [Ben Harriott](https://benharriott.com)"
description = "Lens Based Art"
email = "urbenji@protonmail.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "/images/static1-squarespace-1.png"
phone = "+44 7786 972187"
theme_color = "#41228e"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://twitter.com/urben"
icon = "ti-twitter-alt"
[[params.social]]
URL = "https://www.facebook.com/ben.harriott"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/urben.eth/"
icon = "ti-instagram"
